# Generated by Django 5.0 on 2023-12-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choose_gen',
            field=models.CharField(blank=True, choices=[('man', 'MAN'), ('woman', 'WOMAN'), ('all', 'ALL')], max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='choose_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choose_years', to='chat.years'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gen',
            field=models.CharField(blank=True, choices=[('man', 'MAN'), ('woman', 'WOMAN'), ('all', 'ALL')], max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='chat.years'),
        ),
    ]
