# Generated by Django 5.0 on 2023-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_choose_gen_alter_user_choose_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
